substitutions:
  name: "esp-svitlobot"
  friendly_name: "Svitlo Bot"

esp32:
  board: esp32-c3-devkitm-1

dashboard_import:
  package_import_url: github://andrewjswan/esphome-config/svitlobot_esp32.yaml@main

packages:
  common: !include packages/common.yaml
  svitlobot: !include packages/svitlobot.yaml
  esp32: !include packages/esp32.yaml
  http_ota: !include packages/http_ota.yaml
