substitutions:
  device: "esp_svitlobot"
  name: "svitlobot"
  friendly_name: "Svitlo Bot"

esp32:
  board: nodemcu-32s

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/svitlobot_esp32.yaml@main

packages:
  remote_package:
    url: https://github.com/andrewjswan/svitlobot
    files:
      - packages/common.yaml
      - packages/svitlobot.yaml
      - packages/esp32.yaml
      - packages/http_ota.yaml
    refresh: 1s
