substitutions:
  name: "esp-svitlobot"
  friendly_name: "Svitlo Bot"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

dashboard_import:
  package_import_url: github://andrewjswan/esphome-config/svitlobot_esp8266.yaml@main

packages:
  common: !include packages/common.yaml
  svitlobot: !include packages/svitlobot.yaml
  esp8266: !include packages/esp8266.yaml
