substitutions:
  device: "esp_svitlobot"
  name: "svitlobot"
  friendly_name: "Svitlo Bot"

esp32:
  board: nodemcu-32s

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/svitlobot_esp32.yaml@main

packages:
  common: !include packages/common.yaml
  svitlobot: !include packages/svitlobot.yaml
  esp32: !include packages/esp32.yaml
  http_ota: !include packages/http_ota.yaml
