substitutions:
  name: "esp-svitlobot"
  friendly_name: "Svitlo Bot"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/svitlobot_esp32c3.yaml@main

packages:
  common: !include packages/common.yaml
  svitlobot: !include packages/svitlobot.yaml
  esp32: !include packages/esp32.yaml
  http_ota: !include packages/http_ota.yaml
