substitutions:
  device: "esp_healthcheck"
  name: "healthcheck"
  friendly_name: "Health Check"

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/healthcheck/healthcheck_esp32—Å3.yaml@main

packages:
  remote_package:
    url: https://github.com/andrewjswan/svitlobot
    files:
      - packages/common.yaml
      - packages/healthcheck.yaml
      - packages/esp32.yaml
      - packages/http_ota.yaml
    refresh: 1s
