substitutions:
  device: "esp_svitlobot_atom"
  name: "svitlobot-atom"
  friendly_name: "Svitlo Bot"
  project_name: "ajs.SvitloBot"
  project_version: "3.5.31"
  comment: "ESPHome Svitlo Bot | Shadow"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$device
  project:
    name: "${project_name}"
    version: "${project_version}"

external_components:
  - source:
      type: git
      url: https://github.com/andrewjswan/esphome-components
      ref: main
    components: [shadow]
    refresh: 60s

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/devices/atom-svitlobot.yaml@main

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: web_server
  - platform: http_request

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  ota: false
  log: false
  version: 3

wifi:
  ap: {}  # This spawns an AP with the device name and mac address with no password.
  enable_btm: true
  enable_rrm: true

captive_portal:

http_request:
  useragent: "esphome/${name} (${project_version})"
  verify_ssl: false
  timeout: 15s

globals:
  - id: send_quality
    type: int
    restore_value: no
    initial_value: '-1'

script:
  - id: send_state
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(my_key).has_state();'
          then:
            - light.turn_on:
                id: status_led
                brightness: 50%
                red: 0%
                green: 0%
                blue: 100%
                transition_length: 1s
            - lambda: delay(1000);
            - http_request.get:
                url: !lambda |-
                  return ((std::string) "https://api.svitlobot.in.ua/channelPing?channel_key=" + id(my_key).state).c_str();
                capture_response: false
                on_response:
                  then:
                    # - lambda: id(set_state)->execute(response->status_code, body);
                    - lambda: id(set_state)->execute(response->status_code);
                on_error:
                  then:
                    - script.execute:
                        id: set_state
                        code: -1
                        # response: ""
            - component.update: quality
          else:
            - light.turn_on:
                id: status_led
                brightness: 50%
                red: 100%
                green: 100%
                blue: 0%
                transition_length: 1s
    mode: queued

  - id: set_state
    parameters:
      code: int
      # response: string
    then:
      - lambda: |-
          // if (code == 200 && response.find("Accepted request") != std::string::npos)
          if (code == 200)
          {
            ESP_LOGD("SvitloBot", "Send status - success");
            id(send_status).publish_state(true);
            id(send_quality) = id(send_quality) < 0 ? 100 : std::min(100, ++id(send_quality));

            auto turn_on = id(status_led).turn_on();
            turn_on.set_brightness(0.5);
            turn_on.set_rgb(0.0, 0.5, 0.0);
            turn_on.set_transition_length(1000);
            turn_on.perform();

            delay_microseconds_safe(1000000);  // 1s

            auto turn_off = id(status_led).turn_off();
            turn_off.set_transition_length(1000);
            turn_off.perform();
          }
          else
          {
            if (code > 0)
            {
              ESP_LOGE("SvitloBot", "Send status - not success with response code: %d", code);
            } else {
              ESP_LOGE("SvitloBot", "Request failed!");
            }
            id(send_status).publish_state(false);
            id(send_quality) = id(send_quality) < 0 ? 0 : std::max(0, --id(send_quality));

            auto turn_on = id(status_led).turn_on();
            turn_on.set_brightness(0.5);
            turn_on.set_rgb(0.5, 0.0, 0.0);
            turn_on.set_transition_length(1000);
            turn_on.perform();
          }
    mode: single

shadow:
  id: svitlobot
  script_id: send_state
  interval: 90

light:
  - name: "LED"
    id: status_led
    icon: mdi:lighthouse
    platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 27
    num_leds: 1
    # rmt_channel: 0
    chipset: SK6812
    restore_mode: ALWAYS_OFF
    web_server:
      sorting_weight: 5

text:
  - platform: template
    name: "Key"
    id: my_key
    optimistic: true
    min_length: 0
    max_length: 15
    mode: text
    restore_value: true
    icon: mdi:key-chain-variant
    entity_category: config
    disabled_by_default: true
    web_server:
      sorting_weight: 5

binary_sensor:
  - platform: template
    name: "Status"
    id: send_status
    icon: mdi:lan-connect
    web_server:
      sorting_weight: 3

sensor:
  - platform: template
    name: "Delivery Quality"
    id: quality
    lambda: |-
      if (!id(my_key).has_state() || id(send_quality) < 0)
      {
        return NAN;
      }
      return id(send_quality);
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement
    web_server:
      sorting_weight: 5
    on_value_range:
      - above: 1.0
        below: 90.0
        then:
          - button.press: Restart

  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Signal"
    entity_category: diagnostic
    icon: mdi:signal

  - platform: internal_temperature
    name: "Device Temperature"
    entity_category: diagnostic
    icon: mdi:coolant-temperature
    device_class: temperature
    disabled_by_default: true

button:
  - platform: restart
    name: "Restart"
    id: Restart
    entity_category: diagnostic
    icon: mdi:restart

  - platform: factory_reset
    name: "Restart with Factory Default Settings"
    id: Reset
    entity_category: diagnostic
    disabled_by_default: true

  - platform: template
    name: "Firmware Update"
    icon: mdi:progress-upload
    disabled_by_default: true
    entity_category: config
    on_press:
      - update.perform:
          id: new_firmware

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:ip
    ssid:
      name: "Connected SSID"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:access-point-network
    mac_address:
      name: "Mac Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:console-network

update:
  - platform: http_request
    id: new_firmware
    name: "Firmware Update"
    source: https://andrewjswan.github.io/svitlobot/devices/${name}-manifest.json
    icon: mdi:update
    web_server:
      sorting_weight: 15
