substitutions:
  device: "esp_svitlobot_atom"
  name: "svitlobot-atom"
  friendly_name: "Svitlo Bot"
  path: "devices/"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/devices/atom-svitlobot.yaml@main

packages:
  remote_package:
    url: https://github.com/andrewjswan/svitlobot
    files:
      - packages/common.yaml
      - packages/svitlobot.yaml
      - packages/esp32.yaml
      - packages/http_ota.yaml
    refresh: 1s

script:
  - id: !remove svitlobot_ping
  - id: svitlobot_ping
    then:
      - wait_until:
          condition:
            wifi.connected:
          timeout: 15s
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(svitlobot_key).has_state();'
              - lambda: 'return id(svitlobot_key).state.length() > 3;'
              - lambda: 'return ${lets_ping};'
          then:
            - light.turn_on:
                id: status_led
                brightness: 50%
                red: 0%
                green: 0%
                blue: 100%
                transition_length: 1s
            - lambda: delay(1000);
            - http_request.get:
                url: !lambda |-
                  return ((std::string) "https://api.svitlobot.in.ua/channelPing?channel_key=" + id(svitlobot_key).state).c_str();
                capture_response: false
                on_response:
                  then:
                    - lambda: id(svitlobot_set_state)->execute(response->status_code, response->duration_ms);
                on_error:
                  then:
                    - script.execute:
                        id: svitlobot_set_state
                        code: -1
                        duration: 0
            - component.update: svitlobot_errors
            - if:
                condition:
                  lambda: 'return id(svitlobot_status).state;'
                then:
                  - light.turn_on:
                      id: status_led
                      brightness: 50%
                      red: 0%
                      green: 100%
                      blue: 0%
                      transition_length: 1s
                  - lambda: delay(3000);
                  - light.turn_off:
                      id: status_led
                      transition_length: 1s
                else:
                  - light.turn_on:
                      id: status_led
                      brightness: 50%
                      red: 100%
                      green: 0%
                      blue: 0%
                      transition_length: 1s
          else:
            - light.turn_on:
                id: status_led
                brightness: 50%
                red: 100%
                green: 100%
                blue: 0%
                transition_length: 1s
    mode: queued

light:
  - name: "LED"
    id: status_led
    icon: mdi:lighthouse
    platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 27
    num_leds: 1
    # rmt_channel: 0
    chipset: SK6812
    restore_mode: ALWAYS_OFF
    web_server:
      sorting_weight: 5
