substitutions:
  device: "esp_svitlobot_c3_oled"
  name: "svitlobot-c3-oled"
  friendly_name: "Svitlo Bot"
  project_name: "ajs.SvitloBot"
  project_version: "3.5.33"
  comment: "ESPHome Svitlo Bot | Shadow"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$device
  project:
    name: "${project_name}"
    version: "${project_version}"

external_components:
  - source:
      type: git
      url: https://github.com/andrewjswan/esphome-components
      ref: main
    components: [shadow]
    refresh: 60s

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/devices/c3-oled-svitlobot.yaml@main

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

api:
  reboot_timeout: 0s

ota:
  - platform: esphome
  - platform: web_server
  - platform: http_request

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  ota: false
  log: false
  version: 3
  sorting_groups:
    - id: svitlobot_group
      name: "💡 SvitloBot"
      sorting_weight: 0

wifi:
  ap: {}  # This spawns an AP with the device name and mac address with no password.
  id: oled_wifi
  enable_btm: true
  enable_rrm: true

captive_portal:

improv_serial:

debug:
  update_interval: never

http_request:
  useragent: "esphome/${name} (${project_version})"
  verify_ssl: false
  timeout: 15s

globals:
  - id: send_quality
    type: int
    restore_value: no
    initial_value: '-1'

script:
  - id: send_state
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(my_key).has_state();'
          then:
            - lambda: id(response_code).publish_state(0);
            - http_request.get:
                url: !lambda |-
                  return ((std::string) "https://api.svitlobot.in.ua/channelPing?channel_key=" + id(my_key).state).c_str();
                capture_response: false
                on_response:
                  then:
                    - lambda: id(set_state)->execute(response->status_code);
                on_error:
                  then:
                    - script.execute:
                        id: set_state
                        code: -1
            - component.update: quality
    mode: queued

  - id: set_state
    parameters:
      code: int
    then:
      - lambda: |-
          if (code > 0) {
            id(response_code).publish_state(code);
          } else {
            ESP_LOGE("SvitloBot", "Request failed!");
            id(response_code).publish_state(NAN);
          }

          if (code == 200) {
            ESP_LOGD("SvitloBot", "Send status - success");
            id(send_status).publish_state(true);
            id(send_quality) = id(send_quality) < 0 ? 100 : std::min(100, ++id(send_quality));
          } else {
            if (code > 0) {
              ESP_LOGE("SvitloBot", "Send status - not success with response code: %d", code);
            }
            id(send_status).publish_state(false);
            id(send_quality) = id(send_quality) < 0 ? 0 : std::max(0, --id(send_quality));
          }
    mode: single

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true
  id: bus_i2c

font:
  - file: "gfonts://Roboto"
    id: oled_font
    size: 10

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    id: oled_display
    rotation: 0
    update_interval: 1s
    offset_y: 0
    offset_x: 0
    invert: true
    address: 0x3C
    lambda: |-
      if (id(oled_wifi).is_ap_active()) {
        it.printf(0, 0, id(oled_font), "WiFi: AP");
      } else if (id(oled_wifi).is_connected()) {
        it.printf(0, 0, id(oled_font), "WiFi: ON");
      } else {
        it.printf(0, 0, id(oled_font), "WiFi: OFF");
      }
      if (id(my_key).has_state()) {
        it.printf(0, 10, id(oled_font), "State: %s", ONOFF(id(send_status).state));
        it.printf(0, 20, id(oled_font), "Code: %d", id(response_code).state);
      } else {
        it.printf(0, 10, id(oled_font), "NO KEY");
      }

shadow:
  id: svitlobot
  script_id: send_state
  interval: 90

text:
  - platform: template
    name: "Key"
    id: my_key
    optimistic: true
    min_length: 0
    max_length: 15
    mode: text
    restore_value: true
    icon: mdi:key-chain-variant
    entity_category: config
    disabled_by_default: true
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 5

binary_sensor:
  - platform: template
    name: "Status"
    id: send_status
    icon: mdi:lan-connect
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 1

sensor:
  - platform: template
    name: "Delivery Quality"
    id: quality
    lambda: |-
      if (!id(my_key).has_state() || id(send_quality) < 0) {
        return NAN;
      }
      return id(send_quality);
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 3
    on_value_range:
      - above: 1.0
        below: 90.0
        then:
          - button.press: Restart

  - platform: template
    name: "Response Code"
    id: response_code
    accuracy_decimals: 0
    icon: mdi:web
    entity_category: diagnostic
    disabled_by_default: true
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 10
    on_value:
      then:
        - lambda: |-
            if (std::isnan(x)) {
              id(response_code).set_icon("mdi:web-cancel");
            } else if (x == 0) {
              id(response_code).set_icon("mdi:web-sync");
            } else if (x == 200) {
              id(response_code).set_icon("mdi:web-check");
            } else if (x >= 400) {
              id(response_code).set_icon("mdi:web-remove");
            } else {
              id(response_code).set_icon("mdi:web-clock");
            }

  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Signal"
    entity_category: diagnostic
    icon: mdi:signal

  - platform: internal_temperature
    name: "Device Temperature"
    entity_category: diagnostic
    icon: mdi:coolant-temperature
    device_class: temperature
    disabled_by_default: true

button:
  - platform: restart
    name: "Restart"
    id: Restart
    entity_category: diagnostic
    icon: mdi:restart

  - platform: factory_reset
    name: "Restart with Factory Default Settings"
    id: Reset
    entity_category: diagnostic
    disabled_by_default: true

  - platform: template
    name: "Firmware Update"
    icon: mdi:progress-upload
    disabled_by_default: true
    entity_category: config
    on_press:
      - update.perform:
          id: new_firmware

text_sensor:
  - platform: template
    name: ESPHome Version
    icon: mdi:new-box
    entity_category: diagnostic
    lambda: |-
      return std::string(ESPHOME_VERSION);

  - platform: debug
    reset_reason:
      name: "Reset Reason"
      disabled_by_default: true
      entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:ip
    ssid:
      name: "Connected SSID"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:access-point-network
    mac_address:
      name: "Mac Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:console-network

update:
  - platform: http_request
    id: new_firmware
    name: "Firmware Update"
    source: https://andrewjswan.github.io/svitlobot/devices/${name}-manifest.json
    icon: mdi:update
    web_server:
      sorting_weight: 15
