substitutions:
  device: "esp_svitlobot_s3_geek"
  name: "svitlobot-s3-geek"
  friendly_name: "Svitlo Bot"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/devices/s3-geek-svitlobot.yaml@main

packages:
  remote_package:
    url: https://github.com/andrewjswan/svitlobot
    files:
      - packages/common.yaml
      - packages/svitlobot.yaml
      - packages/esp32.yaml
      - packages/http_ota.yaml
    refresh: 1s

time:
  - platform: sntp
    id: esp_time
    timezone: "Europe/Kiev"
    update_interval: 1h
    on_time_sync:
      then:
        if:
          condition:
            time.has_time:
          then:
            - logger.log: Time has been set and is valid!

globals:
  - id: state_last_event
    type: time_t
    restore_value: no
    initial_value: '0'

font:
  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: font_text_small
    size: 16

  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: font_text_big
    size: 30

  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: font_time_small
    size: 20

  - file:
      type: gfonts
      family: Roboto
      weight: 900
    id: font_time_big
    size: 100

  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/refs/heads/master/fonts/materialdesignicons-webfont.ttf"
    id: font_mdi_small
    size: 40
    glyphs:
      - "\U000F092B"
      - "\U000F0928"
      - "\U000F0925"
      - "\U000F0922"
      - "\U000F091F"
      - "\U000F1792"
      - "\U000F1790"
      - "\U000F0789"
      - "\U000F0551"
      - "\U000F124A"

  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/refs/heads/master/fonts/materialdesignicons-webfont.ttf"
    id: font_mdi_big
    size: 130
    glyphs:
      - "\U000F06E9"
      - "\U000F0ECD"
      - "\U000F1984"

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO11

output:
  - platform: ledc
    pin: GPIO7
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    icon: mdi:tablet-dashboard
    id: display_light
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    disabled_by_default: true

display:
  - platform: mipi_spi
    id: svitlobot_display
    model: ST7789V
    dimensions:
      width: 135
      height: 240
      offset_width: 52
      offset_height: 40
    cs_pin: GPIO10
    dc_pin: GPIO8
    reset_pin: GPIO9
    rotation: 0
    invert_colors: true
    color_depth: 16bit
    # color_order: rgb
    update_interval: 1s
    pages:
      - id: state_page
        lambda: |-
          // Base
          const auto COLOR_WHITE = Color(255, 255, 255);
          const auto COLOR_BLACK = Color(0, 0, 0);
          const auto COLOR_RED = Color(255, 0, 0);
          const auto COLOR_GREEN = Color(0, 255, 0);
          // const auto COLOR_BLUE = Color(0, 0, 255);
          // const auto COLOR_YELLOW = Color(255, 255, 0);
          // const auto COLOR_ORANGE = Color(255, 165, 0);

          auto color_off = COLOR_WHITE;
          auto color_on = COLOR_BLACK;

          if (id(dark_mode).state) {
            color_off = COLOR_BLACK;
            color_on = COLOR_WHITE;
          }

          // Fill
          it.fill(color_off);

          // WiFi Icon
          const char* wifi_icon = "\U000F092B";
          if (id(wifi_signal_dbm).has_state()) {
            float signal = id(wifi_signal_dbm).state;
            if (std::isnan(signal)) signal = -100;
            if (signal >= -50) wifi_icon = "\U000F0928";
            else if (signal >= -60) wifi_icon = "\U000F0925";
            else if (signal >= -75) wifi_icon = "\U000F0922";
            else if (signal >= -100) wifi_icon = "\U000F091F";
            else wifi_icon = "\U000F092B";
          }
          it.printf(20, 20, id(font_mdi_small), color_on, TextAlign::CENTER, "%s", wifi_icon);

          // WiFi Text
          if (id(oled_wifi).is_ap_active()) {
            it.printf(88, 20, id(font_text_big), COLOR_RED, TextAlign::CENTER, "AP");
          } else if (id(oled_wifi).is_connected()) {
            it.printf(88, 20, id(font_text_big), COLOR_GREEN, TextAlign::CENTER, "ON");
          } else {
            it.printf(88, 20, id(font_text_big), color_on, TextAlign::CENTER, "OFF");
          }

          // Code
          if (id(my_key).has_state()) {
            auto x = id(response_code).state;
            if (x.empty()) {
              it.printf(21, 61, id(font_mdi_small), color_on, TextAlign::CENTER, "%s", "\U000F1792");
            } else if (x == "---") {
              it.printf(21, 61, id(font_mdi_small), color_on, TextAlign::CENTER, "%s", "\U000F1790");
            } else {
              int code = atoi(x.c_str());
              if (code == 200) {
                it.printf(21, 61, id(font_mdi_small), color_on, TextAlign::CENTER, "%s", "\U000F0789");
              } else if (code >= 400) {
                it.printf(21, 61, id(font_mdi_small), color_on, TextAlign::CENTER, "%s", "\U000F0551");
              } else {
                it.printf(21, 61, id(font_mdi_small), color_on, TextAlign::CENTER, "%s", "\U000F124A");
              }
            }
            it.printf(88, 61, id(font_text_big), color_on, TextAlign::CENTER, "%s", id(response_code).state.c_str());
          }

          // Big Icon
          if (id(my_key).has_state()) {
            if (id(send_status).state) {
              it.printf(68, 151, id(font_mdi_big), COLOR_GREEN, TextAlign::CENTER, "%s", "\U000F06E9");
            } else {
              it.printf(68, 151, id(font_mdi_big), COLOR_RED, TextAlign::CENTER, "%s", "\U000F0ECD");
            }
          } else {
            it.printf(68, 151, id(font_mdi_big), COLOR_RED, TextAlign::CENTER, "%s", "\U000F1984");
          }

          // IP Adress
          if (id(ip_adress).has_state()) {
            it.printf(68, 230, id(font_text_small), color_on, TextAlign::CENTER, "%s", id(ip_adress).state.c_str());
          }

      - id: time_page
        lambda: |-
          // Base
          const auto COLOR_WHITE = Color(255, 255, 255);
          const auto COLOR_BLACK = Color(0, 0, 0);

          auto color_off = COLOR_WHITE;
          auto color_on = COLOR_BLACK;

          if (id(dark_mode).state) {
            color_off = COLOR_BLACK;
            color_on = COLOR_WHITE;
          }

          // Fill
          it.fill(color_off);

          auto time = id(esp_time).now();
          if (time.is_valid()) {
            std::string day = time.strftime("%A");
            std::transform(day.begin(), day.end(), day.begin(), ::toupper);
            it.printf(68, 15, id(font_time_small), color_on, TextAlign::CENTER, day.c_str());
            it.strftime(68, 75, id(font_time_big), color_on, TextAlign::CENTER, "%H", time);
            it.strftime(68, 165, id(font_time_big), color_on, TextAlign::CENTER, "%M", time);
            it.strftime(68, 226, id(font_time_small), color_on, TextAlign::CENTER, "%d-%m-%Y", time);
          }

interval:
  - interval: 30s
    then:
      - if:
          condition:
            lambda: |-
              return !id(svitlobot_status).state;
          then:
            - light.turn_on: display_light
            - display.page.show: state_page
          else:
            - display.page.show: !lambda |-
                auto time = id(esp_time).now();
                if (!time.is_valid()) {
                  return id(state_page);
                }
                if ((time_t)time.timestamp - id(state_last_event) > 300) {
                  return id(time_page);
                }
                return id(state_page);
            - lambda: |-
                auto time = id(esp_time).now();
                if (time.is_valid()) {
                  if (id(night_mode).state) {
                    if (time.hour = 23 || time.hour < 8) {
                      if ((time_t)time.timestamp - id(state_last_event) > 300) {
                        id(display_light).turn_off().perform();
                        return;
                      }
                    }
                  }
                }
                id(display_light).turn_on().perform();

switch:
  - platform: template
    name: "Dark Mode"
    id: dark_mode
    icon: mdi:monitor-shimmer
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    disabled_by_default: true

  - platform: template
    name: "Night Mode"
    id: night_mode
    icon: mdi:weather-night
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    disabled_by_default: true

binary_sensor:
  - id: !extend svitlobot_status
    on_state:
      then:
        - globals.set:
            id: state_last_event
            value: !lambda |-
              auto time = id(esp_time).now();
              if (!time.is_valid()) {
                return (time_t)0;
              }
              return (time_t)time.timestamp;
    on_release:
      then:
        - display.page.show: state_page
        - light.turn_on: display_light

  - platform: gpio
    name: "Button"
    pin:
      number: GPIO0
      inverted: true
      mode:
        input: true
        pullup: true
    icon: mdi:gesture-tap-box
    id: display_button
    entity_category: config
    disabled_by_default: true
    on_press:
      then:
        - light.toggle: display_light
        - if:
            condition:
              light.is_on: display_light
            then:
              - globals.set:
                  id: state_last_event
                  value: !lambda |-
                    auto time = id(esp_time).now();
                    if (!time.is_valid()) {
                      return (time_t)0;
                    }
                    return (time_t)time.timestamp;
              - display.page.show: state_page
