substitutions:
  device: "esp_svitlobot"
  name: "svitlobot"
  friendly_name: "Svitlo Bot"

esp8266:
  # https://github.com/esphome/firmware/blob/main/esp-web-tools/esp8266.yaml
  # board: esp01_1m
  # board: d1_mini
  board: nodemcuv2
  restore_from_flash: true

dashboard_import:
  package_import_url: github://andrewjswan/svitlobot/svitlobot/svitlobot_esp8266.yaml@main

packages:
  remote_package:
    url: https://github.com/andrewjswan/svitlobot
    files:
      - packages/common.yaml
      - packages/svitlobot.yaml
      - packages/esp8266.yaml
      - packages/http_ota.yaml
    refresh: 1s
