esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  # name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$device
  project:
    name: "${project_name}"
    version: "${project_version}"

api:
  reboot_timeout: 0s

ota:
  - platform: esphome

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  log: false
  version: 3

wifi:
  ap: {}

captive_portal:

improv_serial:

sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

  - platform: wifi_signal
    name: "WiFi Signal"
    entity_category: diagnostic
    icon: mdi:signal

button:
  - platform: restart
    name: "Restart"
    id: Restart
    entity_category: diagnostic
    icon: mdi:restart

  - platform: factory_reset
    name: "Restart with Factory Default Settings"
    id: Reset
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: version
    name: ESPHome Version
    hide_timestamp: true
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "IP Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:ip
    ssid:
      name: "Connected SSID"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:access-point-network
    mac_address:
      name: "Mac Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:console-network
