substitutions:
  project_name: "ajs.Custom_URL"
  project_version: "3.5.37"

http_request:
  useragent: "esphome/${name} (${project_version})"
  verify_ssl: false
  timeout: 15s

globals:
  - id: custom_url_send_quality
    type: int
    restore_value: no
    initial_value: '-1'

web_server:
  version: 3
  sorting_groups:
    - id: custom_url_group
      name: "🤖 Custom URL"
      sorting_weight: 3

script:
  - id: !extend site_ping
    then:
      - logger.log: "Custom URL..."
      - script.execute: custom_url_ping
      - script.wait: custom_url_ping

  - id: custom_url_ping
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(custom_url).has_state();'
          then:
            - http_request.get:
                url: !lambda |-
                  return ((std::string) id(custom_url).state).c_str();
                capture_response: false
                on_response:
                  then:
                    - lambda: id(custom_url_set_state)->execute(response->status_code, response->duration_ms);
                on_error:
                  then:
                    - script.execute:
                        id: custom_url_set_state
                        code: -1
                        duration: 0
            - component.update: custom_url_quality
    mode: queued

  - id: custom_url_set_state
    parameters:
      code: int
      duration: int
    then:
      - lambda: |-
          if (code > 0) {
            id(custom_url_response_code).publish_state(std::to_string(code));
          } else {
            ESP_LOGE("Custom URL", "Request failed!");
            id(custom_url_response_code).publish_state("---");
          }

          if (duration > 0) {
            id(custom_url_response_duration).publish_state(duration);
          } else {
            id(custom_url_response_duration).publish_state(NAN);
          }

          if (code == 200) {
            ESP_LOGD("Custom URL", "Send status - success");
            id(custom_url_status).publish_state(true);
            id(custom_url_send_quality) = id(custom_url_send_quality) < 0 ? 100 : std::min(100, ++id(custom_url_send_quality));
          } else {
            if (code > 0) {
              ESP_LOGE("Custom URL", "Send status - not success with response code: %d", code);
            }
            id(custom_url_status).publish_state(false);
            id(custom_url_send_quality) = id(custom_url_send_quality) < 0 ? 0 : std::max(0, --id(custom_url_send_quality));
          }
    mode: single

text:
  - platform: template
    name: "Custom URL"
    id: custom_url
    optimistic: true
    mode: text
    restore_value: true
    icon: mdi:webhook
    entity_category: config
    disabled_by_default: true
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 5

binary_sensor:
  - platform: template
    name: "Status"
    id: custom_url_status
    icon: mdi:lan-connect
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 1

sensor:
  - platform: template
    name: "Delivery Quality"
    id: custom_url_quality
    lambda: |-
      if (!id(custom_url).has_state() || id(custom_url_send_quality) < 0) {
        return NAN;
      }
      return id(custom_url_send_quality);
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 3
    on_value_range:
      - above: 1.0
        below: 90.0
        then:
          - button.press: Restart

  - platform: template
    name: "Response Duration"
    id: custom_url_response_duration
    icon: mdi:timer-outline
    entity_category: diagnostic
    disabled_by_default: true
    device_class: duration
    unit_of_measurement: "ms"
    accuracy_decimals: 0
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 11

text_sensor:
  - platform: template
    name: "Response Code"
    id: custom_url_response_code
    icon: mdi:web
    entity_category: diagnostic
    disabled_by_default: true
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 10
    on_value:
      then:
        - lambda: |-
            if (x.empty()) {
              id(custom_url_response_code).set_icon("mdi:web-sync");
            } else if (x == "---") {
              id(custom_url_response_code).set_icon("mdi:web-cancel");
            } else {
              int code = atoi(x.c_str());
              if (code == 200) {
                id(custom_url_response_code).set_icon("mdi:web-check");
              } else if (code >= 400) {
                id(custom_url_response_code).set_icon("mdi:web-remove");
              } else {
                id(custom_url_response_code).set_icon("mdi:web-clock");
              }
            }
