substitutions:
  project_name: "ajs.SvitloBot"
  project_version: "3.5.41"

http_request:
  useragent: "esphome/${name} (${project_version})"
  verify_ssl: false
  timeout: 15s

globals:
  - id: svitlobot_send_errors
    type: int
    restore_value: no
    initial_value: '-1'

web_server:
  version: 3
  sorting_groups:
    - id: svitlobot_group
      name: "💡 SvitloBot"
      sorting_weight: -5

script:
  - id: !extend site_ping
    then:
      - logger.log: "SvitloBot..."
      - script.execute: svitlobot_ping
      - script.wait: svitlobot_ping

  - id: svitlobot_ping
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(svitlobot_key).has_state();'
              - lambda: 'return ${lets_ping};'
          then:
            - http_request.get:
                url: !lambda |-
                  return ((std::string) "https://api.svitlobot.in.ua/channelPing?channel_key=" + id(svitlobot_key).state).c_str();
                capture_response: false
                on_response:
                  then:
                    - lambda: id(svitlobot_set_state)->execute(response->status_code, response->duration_ms);
                on_error:
                  then:
                    - script.execute:
                        id: svitlobot_set_state
                        code: -1
                        duration: 0
            - component.update: svitlobot_errors
    mode: single

  - id: svitlobot_set_state
    parameters:
      code: int
      duration: int
    then:
      - lambda: |-
          if (code > 0) {
            id(svitlobot_response_code).publish_state(std::to_string(code));
          } else {
            ESP_LOGE("SvitloBot", "Request failed!");
            id(svitlobot_response_code).publish_state("---");
          }

          if (duration > 0) {
            id(svitlobot_response_duration).publish_state(duration);
          } else {
            id(svitlobot_response_duration).publish_state(NAN);
          }

          if (code == 200) {
            ESP_LOGD("SvitloBot", "Send status - success");
            id(svitlobot_status).publish_state(true);
            id(svitlobot_send_errors) = 0;
          } else {
            if (code > 0) {
              ESP_LOGE("SvitloBot", "Send status - not success with response code: %d", code);
            }
            id(svitlobot_status).publish_state(false);
            id(svitlobot_send_errors) = id(svitlobot_send_errors) < 0 ? 1 : std::max(1, ++id(svitlobot_send_errors));
          }
    mode: single

text:
  - platform: template
    name: "Key"
    id: svitlobot_key
    optimistic: true
    min_length: 0
    max_length: 15
    mode: text
    restore_value: true
    icon: mdi:key-chain-variant
    entity_category: config
    disabled_by_default: true
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 5

binary_sensor:
  - platform: template
    name: "Status"
    id: svitlobot_status
    icon: mdi:lan-connect
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 1

sensor:
  - platform: template
    name: "Delivery Errors"
    id: svitlobot_errors
    lambda: |-
      if (!id(svitlobot_key).has_state() || id(svitlobot_send_errors) < 0) {
        return NAN;
      }
      return id(svitlobot_send_errors);
    accuracy_decimals: 0
    icon: mdi:space-invaders
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 3
    on_value_range:
      - above: 10.0
        then:
          - button.press: Restart

  - platform: template
    name: "Response Duration"
    id: svitlobot_response_duration
    icon: mdi:timer-outline
    entity_category: diagnostic
    disabled_by_default: true
    device_class: duration
    unit_of_measurement: "ms"
    accuracy_decimals: 0
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 11

text_sensor:
  - platform: template
    name: "Response Code"
    id: svitlobot_response_code
    icon: mdi:web
    entity_category: diagnostic
    disabled_by_default: true
    web_server:
      sorting_group_id: svitlobot_group
      sorting_weight: 10
    on_value:
      then:
        - lambda: |-
            if (x.empty()) {
              id(svitlobot_response_code).set_icon("mdi:web-sync");
            } else if (x == "---") {
              id(svitlobot_response_code).set_icon("mdi:web-cancel");
            } else {
              int code = atoi(x.c_str());
              if (code == 200) {
                id(svitlobot_response_code).set_icon("mdi:web-check");
              } else if (code >= 400) {
                id(svitlobot_response_code).set_icon("mdi:web-remove");
              } else {
                id(svitlobot_response_code).set_icon("mdi:web-clock");
              }
            }
