substitutions:
  project_name: "ajs.SvitloBot"
  project_version: "3.5.19"

http_request:
  useragent: "esphome/${name} (${project_version})"
  verify_ssl: false
  timeout: 10s

globals:
  - id: send_quality
    type: int
    restore_value: no
    initial_value: '-1'

  - id: session
    type: bool
    restore_value: no
    initial_value: 'false'

script:
  - id: send_state
    then:
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(my_key).has_state();'
          then:
            - globals.set:
                id: session
                value: 'true'
            - http_request.get:
                url: !lambda |-
                  return ((std::string) "https://api.svitlobot.in.ua/channelPing?channel_key=" + id(my_key).state).c_str();
                on_response:
                  then:
                    - lambda: id(set_state)->execute(response->status_code, "");
                    - globals.set:
                        id: session
                        value: 'false'
            - if:
                condition:
                  lambda: 'return id(session);'
                then:
                  - script.execute:
                      id: set_state
                      code: -1
                      response: ""
            - component.update: quality
    mode: queued

  - id: set_state
    parameters:
      code: int
      response: string
    then:
      - lambda: |-
          if (code == 200)
          {
            ESP_LOGD("SvitloBot", "Send status - success");
            id(send_status).publish_state(true);
            id(send_quality) = id(send_quality) < 0 ? 100 : std::min(100, ++id(send_quality));
          }
          else
          {
            if (code > 0)
            {
              ESP_LOGE("SvitloBot", "Send status - not success with response code: %d", code);
            }
            id(send_status).publish_state(false);
            id(send_quality) = id(send_quality) < 0 ? 0 : std::max(0, --id(send_quality));
          }
    mode: single

text:
  - platform: template
    name: "${friendly_name} Key"
    id: my_key
    optimistic: true
    min_length: 0
    max_length: 15
    mode: text
    restore_value: true
    icon: mdi:key-chain-variant
    entity_category: config
    disabled_by_default: true
    web_server_sorting_weight: 5

binary_sensor:
  - platform: template
    name: "${friendly_name} Status"
    id: send_status
    icon: mdi:lan-connect
    web_server_sorting_weight: 3

sensor:
  - platform: template
    name: "${friendly_name} Delivery Quality"
    id: quality
    lambda: |-
      if (!id(my_key).has_state() || id(send_quality) < 0)
      {
        return NAN;
      }
      return id(send_quality);
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:wan
    state_class: measurement
    web_server_sorting_weight: 5
    on_value_range:
      - above: 1.0
        below: 90.0
        then:
          - button.press: Restart
