name: Build

on:
  push:
    branches: 
      - main
    tags-ignore:
      - '**'  
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  configuration:
    name: Build configuration list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: echo "matrix=$(ls *.yaml | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    name: Build ${{ matrix.config-file }}
    needs: configuration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config-file: ${{ fromJson(needs.configuration.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build firmware
        uses: esphome/build-action@v4
        id: esphome-build
        with:
          yaml-file: ${{ matrix.config-file }}
          version: latest
          complete-manifest: true
      - name: Move files to output
        run: |
          mkdir -p output
          mv ${{ steps.esphome-build.outputs.name }}/* output/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.esphome-build.outputs.name }}
          path: output

  combine:
    name: Combine manifests
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: files

      - name: Get artifact names
        id: artifacts
        run: |
          artifacts=$(ls --format=single-column files)
          echo "artifacts<<EOF" >> $GITHUB_OUTPUT
          echo "$artifacts" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5.0.0
        with:
          name: ${{ steps.artifacts.outputs.artifacts }}

      - name: Combine all parts into a single manifest
        run: |
          mkdir -p "output"
          pushd files
          for device in *; do
            pushd $device
            cp * "../../../output/"
            popd
          done
          popd
          jq -s '(.[0] | del(.builds)) + {"builds": (reduce .[].builds as $b ([]; . + $b))}' files/*/manifest.json > output/manifest.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SvitloBot
          path: output

  ci-status:
    name: Status
    runs-on: ubuntu-latest
    needs:
      - combine
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
